# Generated by Django 4.2 on 2024-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='capacityBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('designation', models.CharField(choices=[('student', 'Student'), ('primary teacher', 'Primary Teacher'), ('secondary teacher', 'Secondary Teacher'), ('other', 'Other')], max_length=20)),
                ('specify', models.CharField(blank=True, max_length=122, null=True)),
                ('workplace', models.CharField(blank=True, max_length=122, null=True)),
                ('resident', models.CharField(choices=[('residential', 'Residential'), ('non residential', 'Non Residential')], max_length=20)),
                ('district', models.CharField(blank=True, max_length=122, null=True)),
                ('venue', models.CharField(blank=True, max_length=122, null=True)),
                ('discipline', models.CharField(blank=True, choices=[('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Netball', 'Netball'), ('Badminton', 'Badminton'), ('Basketball', 'Basketball'), ('Athletics', 'Athletics'), ('Mind games', 'Mind games'), ('Media', 'Media'), ('Tennis', 'Tennis'), ('Table tennis', 'Table tennis'), ('Handball', 'Handball'), ('Woodball', 'Woodball'), ('Rugby', 'Rugby'), ('First Aid & Injury MGT', 'First Aid & Injury MGT'), ('Beach soccer', 'Beach soccer'), ('Beach Volleyball', 'Beach Volleyball')], max_length=122, null=True)),
            ],
        ),
    ]
