# Generated by Django 4.2 on 2024-02-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitybuilding',
            name='specify',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
