# Generated by Django 4.2 on 2024-02-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Press Conference', 'Press Conference'), ('Engagement', 'Engagement'), ('Symposium', 'Symposium'), ('Meeting', 'Meeting'), ('Webinar', 'Webinar'), ('Seminar', 'Seminar'), ('Conference', 'Conference'), ('Training', 'Training'), ('Trivial', 'Trivial')], max_length=250),
        ),
    ]
