# Generated by Django 4.2 on 2024-12-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='capacityBuilding',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
    ]
