# Generated by Django 4.2 on 2024-02-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('media_house', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('Newspapper', 'Newspapper'), ('TV', 'TV'), ('Magazine', 'Magazine'), ('Radio', 'Radio'), ('Online streaming', 'Online streaming'), ('Blog', 'Blog'), ('Social media channel', 'Social media channel'), ('online news portal', 'online news portal')], max_length=50, null=True)),
                ('role', models.CharField(blank=True, choices=[('Media Officer', 'Media Officer'), ('Editor', 'Editor'), ('Journalist', 'Journalist'), ('photographer', 'photographer'), ('Presenter', 'Presenter'), ('Reporter', 'Reporter'), ('TV/Video Journalist', 'TV/Video Journalist'), ('Commentater', 'Commentater'), ('Media Manager', 'Media Manager')], max_length=19, null=True)),
                ('bio', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_photo', models.ImageField(blank=True, default='http://localhost:8000/static/images/profile.png', null=True, upload_to='photo/')),
                ('office_id', models.ImageField(blank=True, default='http://localhost:8000/static/images/profile.png', null=True, upload_to='ids/')),
                ('nid', models.ImageField(blank=True, default='http://localhost:8000/static/images/profile.png', null=True, upload_to='ids/')),
                ('NIN', models.CharField(blank=True, max_length=122, null=True, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('agree_to_terms', models.BooleanField(default=False, help_text='Check this box if you agree to the terms and conditions.', verbose_name='Agree to Terms')),
            ],
        ),
    ]
