# Generated by Django 4.2 on 2024-02-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='sport',
            field=models.CharField(blank=True, choices=[('Athletics', 'Athletics'), ('Badminton', 'Badminton'), ('Basketball', 'Basketball'), ('Beach soccer', 'Beach soccer'), ('Dance sport', 'Dance sport'), ('Football', 'Football'), ('Hockey', 'Hockey'), ('Lacrosse', 'Lacrosse'), ('Rugby', 'Rugby'), ('Volleyball', 'Volleyball'), ('Volleyball', 'Volleyball'), ('Netball', 'Netball'), ('Table Tennis', 'Table Tennis'), ('Tennis', 'Tennis'), ('Swimming', 'Swimming'), ('Handball', 'Handball'), ('Woodball', 'Woodball'), ('Cricket', 'Cricket'), ('Mind Games', 'Mind Games')], max_length=15, null=True),
        ),
    ]
