# Generated by Django 4.2 on 2024-12-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_media_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='sport',
        ),
    ]
