# Generated by Django 4.2 on 2024-02-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='NIN',
            field=models.CharField(blank=True, max_length=122, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agree_to_terms',
            field=models.BooleanField(default=False, help_text='Check this box if you agree to the terms and conditions.', verbose_name='Agree to Terms'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='media_house',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='media_type',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nid',
            field=models.ImageField(blank=True, default='http://localhost:8000/static/images/profile.png', null=True, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office_id',
            field=models.ImageField(blank=True, default='http://localhost:8000/static/images/profile.png', null=True, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='http://localhost:8000/static/images/profile.png', null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Media Officer', 'Media Officer'), ('Editor', 'Editor'), ('Journalist', 'Journalist'), ('photographer', 'photographer'), ('Presenter', 'Presenter'), ('Reporter', 'Reporter'), ('TV/Video Journalist', 'TV/Video Journalist'), ('Commentater', 'Commentater'), ('Media Manager', 'Media Manager')], max_length=19, null=True),
        ),
    ]
