# Generated by Django 5.1.7 on 2025-12-26 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('media_house', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('Newspapper', 'Newspapper'), ('TV', 'TV'), ('Magazine', 'Magazine'), ('Radio', 'Radio'), ('Online streaming', 'Online streaming'), ('Blog', 'Blog'), ('Social media channel', 'Social media channel'), ('online news portal', 'online news portal')], max_length=50, null=True)),
                ('role', models.CharField(blank=True, choices=[('Media Officer', 'Media Officer'), ('Editor', 'Editor'), ('Journalist', 'Journalist'), ('photographer', 'photographer'), ('Presenter', 'Presenter'), ('Reporter', 'Reporter'), ('TV/Video Journalist', 'TV/Video Journalist'), ('Commentater', 'Commentater'), ('Media Manager', 'Media Manager')], max_length=19, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('profile_photo', models.ImageField(default='https://cdn-icons-png.flaticon.com/512/3135/3135715.png', upload_to='photo/')),
                ('office_id', models.ImageField(blank=True, default='http://localhost:8000/static/images/profile.png', null=True, upload_to='ids/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='pending', max_length=10)),
                ('agree_to_terms', models.BooleanField(default=False, help_text='Check this box if you agree to the terms and conditions.', verbose_name='Agree to Terms')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journalist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
